name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual mode

jobs:
  build:
    runs-on: ubuntu-latest # Select an operating system

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Build project
      run: mvn package

    - name: Run unit tests
      run: mvn test

    - name: Commit changes
      run: |
        git config --global user.name 'CI'
        git config --global user.email 'khrystynadukh@gmail.com'
        git add .
        git commit -m "CI: Automated build and test"
        git push
